apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron-server-deployment
  labels:
    app: cron-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cron-server
  template:
    metadata:
      labels:
        app: cron-server
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
        - name: cron-server
          image: mahtovivek741/k8-cron-server
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["SYS_ADMIN"]
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flaskapi-secrets
                  key: db_root_password
            - name: DB_NAME
              value: 'explorun'
            - name: DB_USER_NAME
              value: 'root'
            - name: DB_PORT
              value: '3306'
            - name: DB_SERVER
              value: mysql